---

- name: Check for PVE user {{ item }}
  shell: 'pvesh get /access/users --noborder 1 --noheader 1 | grep "^{{ item }}@pam" -q'
  register: pveacl_user_exists
  ignore_errors: true
  changed_when: false
  check_mode: false
  when: proxmox_pveadmins is defined
- name: Create PVE user {{ item }}
  command: 'pveum useradd {{ item }}@pam'
  when: pveacl_user_exists.rc != 0 and proxmox_pveadmins is defined

- name: Check if PVE user {{ item }} is in group admin
  lineinfile:
    path: '/etc/pve/user.cfg'
    regexp: '^group:admin.*{{ item }}@pam.*'
    state: absent
  register: pveuser_is_admin
  check_mode: true
  changed_when: false
- name: Add PVE user to admin group
  command: 'pveum usermod {{ item }}@pam -group admin'
  when: pveuser_is_admin.found is defined and not pveuser_is_admin.found and proxmox_pveadmins is defined
